version: "3.2"
services:
  acquire-sackson-driver:
    build: .    
    container_name: acquire-sackson-driver
    volumes:
      - type: bind
        source: .
        target: /usr/lib/sackson
      # We need to include required libraries in a volume, so they are available when building the plugin.
      # Vendoring is not an option here, as you can only type assert types from values looked up from 
      # plugins that are defined outside of the plugin.
      # See https://stackoverflow.com/questions/42388090/go-1-8-plugin-use-custom-interface
      - type: bind
        source: /Users/severa/Documents/repos/go/src
        target: /go/src    
    command: ash -c "go build -buildmode=plugin -o /usr/lib/sackson/acquire.so"
